# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b53047a7699fa5282cf8cab4f4a58bb257f2e7f8c66feacbf0416d8d931934620c11c07e1ac149f3524f78b2e7b48a8e649e2132d98f7e05f759453b5f46b1c

test:
  secret_key_base: 51b56f1c3b58e76e06bfb51cb2ed3aa067806ff4086cf219f180e14fda45bd8271c89474161b7eaaac7a2889149712c67e7bd212d98e71f54904a1007909a701

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
